#redis连接配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: redis6380
    port: 6380
    timeout: 300s #连接超时时间，建议不小于redis配置的tcp keepalive(默认300秒)
    lettuce:
      pool:
        max-active: 100 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间(负数表示无限制)
      shutdown-timeout: 100ms