server:
  port: 8088
  servlet:
    context-path: /qs
spring:
  profiles:
    include: redis
  application:
    name: quick-sand
  mvc:
    pathmatch:
      #解决swagger3启动包找不到请求路径NPE问题
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

cust:
  #是否截取票据承兑人括号前内容
  sub-bill-acceptance-left-brackets: true