#redis连接配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: gynshkjit21830
    port: 6388
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: 1000