server:
  port: 8088
  servlet:
    context-path: /qs
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: redis,datasource,ssh2
  application:
    name: quick-sand
  mvc:
    pathmatch:
      #解决swagger3启动包找不到请求路径NPE问题
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

# 日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    name: qs-server
    path: ./logs

#代理设置
proxy:
  enable: false  #[true/false]
  host: 127.0.0.1
  port: 10809

cust:
  #是否截取票据承兑人括号前内容
  sub-bill-acceptance-left-brackets: true
