#redis连接配置
spring:
  redis:
    database: 0
    host: 1.116.137.249
    password: gynshkjit21830
    port: 6388
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: 1000